// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgw-lhimlN3_18GLeVKMn3fIL4Rpz04HA',
    appId: '1:462038358518:web:97aa77e28503d622cccfd7',
    messagingSenderId: '462038358518',
    projectId: 'fooddeliveryapp-77858',
    authDomain: 'fooddeliveryapp-77858.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-77858.appspot.com',
    measurementId: 'G-LWR2HSEM8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDE3hBhZMrxL0wyy_kJZOuFHvTATEoQP8',
    appId: '1:462038358518:android:d20d38a8b01d3cc0cccfd7',
    messagingSenderId: '462038358518',
    projectId: 'fooddeliveryapp-77858',
    storageBucket: 'fooddeliveryapp-77858.appspot.com',
  );
}
